# GET users request
GET http://localhost:5000/users/

###

# GET sorted users request
GET http://localhost:5000/users?_sort=id&_order=desc

###

# GET paginated users request
GET http://localhost:5000/users?_page=5&_limit=10

###

# DELETE request
GET http://localhost:5000/users/9
